spring:
  config:
    import: application-oauth.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        auto_quote_keyword: true

logging.level:
  org.hibernate.SQL: debug